# Adding Cloud Opacity, Scattering, Assymetry


Clouds play a critical role in shaping your reflected light spectrum. 

Until it's release, we will guide you through the file format of the cloud input.

In [1]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import astropy.units as u
from picaso import test as test


#picaso
from picaso import justdoit as jdi 
from picaso import justplotit as jpi
#plotting
from bokeh.io import output_notebook
output_notebook()
from bokeh.plotting import show

Loading BokehJS ...

In [33]:
nlevel=50
ssa=.999

opa = jdi.opannection()

start_case=jdi.inputs()
start_case.phase_angle(0) #radians
start_case.gravity(gravity = 25, gravity_unit=u.Unit('m/(s**2)'))
start_case.approx(raman='none',delta_eddington='False')
start_case.star(opa, 6000,0.0122,4.437) #kelvin, log metal, log cgs
start_case.inputs['test_mode'] = 'other'

start_case.atmosphere(df=pd.DataFrame({'pressure':np.logspace(-6,3,nlevel),
                                    'temperature':np.logspace(-6,3,nlevel)*0+1000 ,
                                    'H2':np.logspace(-6,3,nlevel)*0+0.99, 
                                     'H2O':np.logspace(-6,3,nlevel)*0+0.01,      }))

start_case.clouds(df=pd.DataFrame({'opd':np.zeros(196*(nlevel-1)) + 0.1,
                                    'w0':np.zeros(196*(nlevel-1)) + ssa ,
                                    'g0':np.zeros(196*(nlevel-1)) + 0.0}))

df = start_case.spectrum(opa, calculation='reflected',full_output=True)
wno, alb, fpfs = df['wavenumber'] , df['albedo'] , df['fpfs_reflected'] 

In [34]:
df3 = start_case.spectrum(opa, calculation='reflected',full_output=True,approximation='4stream',stream=2)
wno3, alb3, fpfs3 = df3['wavenumber'] , df3['albedo'] , df3['fpfs_reflected'] 

In [35]:
df4 = start_case.spectrum(opa, calculation='reflected',full_output=True,approximation='4stream',stream=4)
wno4, alb4, fpfs4 = df4['wavenumber'] , df4['albedo'] , df4['fpfs_reflected'] 

In [36]:
show(jpi.spectrum(wno, [alb, alb3, alb4], plot_width=500))

In [6]:
alb[0]-alb3[0]

2.8772774383054034e-05

In [7]:
alb[0]-alb4[0]

-0.0009867611770923573

In [8]:
import pickle as pk
xint_top = pk.load(open('xint_at_top1.pk','rb'))
xint2_top = pk.load(open('xint_at_top_2.pk','rb'))
xint4_top = pk.load(open('xint_at_top_4.pk','rb'))

In [9]:
xint_top.shape

(5, 1, 10)

In [10]:
xint_top[4,0,:]

array([0.02605024, 0.02605024, 0.02605024, 0.02605024, 0.02605024,
       0.02605024, 0.02605024, 0.02605024, 0.02605024, 0.02605024])

In [11]:
xint2_top[4,0,:]

array([0.02662832, 0.02662831, 0.0266283 , 0.0266283 , 0.02662829,
       0.02662828, 0.02662828, 0.02662827, 0.02662826, 0.02662825])

In [12]:
xint4_top[4,0,:]

array([0.02722339, 0.02722339, 0.02722339, 0.02722338, 0.02722338,
       0.02722337, 0.02722337, 0.02722336, 0.02722336, 0.02722335])

In [13]:
ng=1
xint_top[:,0,0]-xint2_top[:,0,0]

array([ 0.0011249 ,  0.0008932 ,  0.00030291, -0.00040404, -0.00057808])

In [14]:
df['flux'][:,0]

array([1.09020794e-09, 4.29034394e-02, 2.75432087e-09, 4.29034383e-02,
       5.29445260e-09, 4.29034365e-02, 9.17175504e-09, 4.29034338e-02,
       1.50901384e-08, 4.29034298e-02, 2.41240636e-08, 4.29034236e-02,
       3.79136056e-08, 4.29034141e-02, 5.89622015e-08, 4.29033996e-02,
       9.10911360e-08, 4.29033775e-02, 1.40133272e-07, 4.29033437e-02,
       2.14991958e-07, 4.29032922e-02, 3.29257344e-07, 4.29032135e-02,
       5.03673482e-07, 4.29030935e-02, 7.69904011e-07, 4.29029103e-02,
       1.17627982e-06, 4.29026306e-02, 1.79657155e-06, 4.29022037e-02,
       2.74337832e-06, 4.29015520e-02, 4.18855997e-06, 4.29005573e-02,
       6.39441519e-06, 4.28990391e-02, 9.76124853e-06, 4.28967217e-02,
       1.48999223e-05, 4.28931847e-02, 2.27424720e-05, 4.28877863e-02,
       3.47106524e-05, 4.28795475e-02, 5.29725092e-05, 4.28669748e-02,
       8.08323898e-05, 4.28477910e-02, 1.23322478e-04, 4.28185260e-02,
       1.88096924e-04, 4.27738956e-02, 2.86776234e-04, 4.27058651e-02,
      

In [15]:
df3['flux'][:,0]

array([0.00000000e+00, 4.29034402e-02, 1.09020794e-09, 4.29034394e-02,
       2.75432088e-09, 4.29034383e-02, 5.29445261e-09, 4.29034365e-02,
       9.17175504e-09, 4.29034338e-02, 1.50901385e-08, 4.29034298e-02,
       2.41240637e-08, 4.29034236e-02, 3.79136056e-08, 4.29034141e-02,
       5.89622015e-08, 4.29033996e-02, 9.10911361e-08, 4.29033775e-02,
       1.40133272e-07, 4.29033437e-02, 2.14991958e-07, 4.29032922e-02,
       3.29257344e-07, 4.29032135e-02, 5.03673482e-07, 4.29030935e-02,
       7.69904011e-07, 4.29029103e-02, 1.17627982e-06, 4.29026306e-02,
       1.79657155e-06, 4.29022037e-02, 2.74337832e-06, 4.29015520e-02,
       4.18855997e-06, 4.29005573e-02, 6.39441519e-06, 4.28990391e-02,
       9.76124853e-06, 4.28967217e-02, 1.48999223e-05, 4.28931847e-02,
       2.27424720e-05, 4.28877863e-02, 3.47106524e-05, 4.28795475e-02,
       5.29725092e-05, 4.28669748e-02, 8.08323898e-05, 4.28477910e-02,
       1.23322478e-04, 4.28185260e-02, 1.88096924e-04, 4.27738956e-02,
      