In [1]:
from math import pi

import pandas as pd

from bokeh.io import show
from bokeh.models import BasicTicker, ColorBar, LinearColorMapper, PrintfTickFormatter
from bokeh.plotting import figure
from bokeh.sampledata.unemployment1948 import data
from bokeh.palettes import viridis
from bokeh.io import output_notebook
output_notebook()
import picaso.justplotit as jpi

import picaso.picaso_data as ptest
import picaso.disort_disco as dtest

import numpy as np

Loading BokehJS ...

/Users/crooney/anaconda3/envs/conda_venv/lib/python3.8/site-packages/pysynphot-1.0.0-py3.8-macosx-10.9-x86_64.egg/pysynphot/locations.py:345: UserWarning: Extinction files not found in /Users/crooney/Documents/codes/all-data/stellar/grp/hst/cdbs/extinction
  warnings.warn('Extinction files not found in %s' % (extdir, ))
/Users/crooney/anaconda3/envs/conda_venv/lib/python3.8/site-packages/pysynphot-1.0.0-py3.8-macosx-10.9-x86_64.egg/pysynphot/refs.py:117: UserWarning: No graph or component tables found; functionality will be SEVERELY crippled. No files found for /Users/crooney/Documents/codes/all-data/stellar/grp/hst/cdbs/mtab/*_tmg.fits
  warnings.warn('No graph or component tables found; '
/Users/crooney/anaconda3/envs/conda_venv/lib/python3.8/site-packages/pysynphot-1.0.0-py3.8-macosx-10.9-x86_64.egg/pysynphot/refs.py:124: UserWarning: No thermal tables found, no thermal calculations can be performed. No files found for /Users/crooney/Documents/codes/all-data/stellar/grp/hst/cdbs/mta

In [3]:
DE = True

# Toon quadrature
Toon_quad = ptest.picaso_albedos(output_dir='Toon_quad.csv', delta_eddington=True, disort_data=True)
# Toon eddington
# Toon_edd = ptest.picaso_albedos(output_dir= 'Toon_eddd.csv',Toon_coefficients ="eddington", delta_eddington=DE)
# SH 2-stream
SH2 = ptest.picaso_albedos(output_dir='SH2.csv',method="SH", delta_eddington=DE, rayleigh=False, disort_data=True)
# SH 4-stream
SH4 = ptest.picaso_albedos(output_dir='SH4.csv',method='SH', stream=4, delta_eddington=True, rayleigh=False, disort_data=True)

YOU ARE REQUESTING RESAMPLING!!
RUN DISORT CODE NOW
YOU ARE REQUESTING RESAMPLING!!
RUN DISORT CODE NOW
YOU ARE REQUESTING RESAMPLING!!
RUN DISORT CODE NOW


In [ ]:
disort = dtest.disort_albedos(output_dir='disort.csv')

In [4]:
# read in data from picaso function
data_old = pd.read_csv('DLUGACH_TEST.csv',index_col=0)
data_disort = pd.read_csv('disort.csv',index_col=0)
data_SH2 = pd.read_csv('SH2.csv',index_col=0)
data_SH4 = pd.read_csv('SH4.csv',index_col=0)
data_quad = pd.read_csv('Toon_quad.csv',index_col=0)
data_edd = pd.read_csv('Toon_eddd.csv',index_col=0)

#If you want to compare two different files for the heatmap just do this
data_compare = data_old
compare_quad = (data_compare-data_quad)/data_compare*100   
compare_edd = (data_compare-data_edd)/data_compare*100   
compare_SH2 = (data_compare-data_SH2)/data_compare*100 
compare_SH4 = (data_compare-data_SH4)/data_compare*100  
compare_SH = (data_SH2-data_SH4)/data_SH2*100    

quad_SH4 = (data_quad-data_SH4)/data_quad*100 
quad_SH2 = (data_quad-data_SH2)/data_quad*100 
edd_SH2 = (data_edd-data_SH2)/data_edd*100 

disort_dlugach = (data_old-data_disort)/data_old*100 

In [ ]:
show(jpi.create_heat_map(disort_dlugach, rayleigh=True))

In [5]:
show(jpi.create_heat_map(quad_SH4, rayleigh=False))

In [7]:
show(jpi.create_heat_map(quad_SH2, rayleigh=False))

In [ ]:
show(jpi.create_heat_map(compare_SH, rayleigh=False))

In [13]:
import pickle as pk
toon_dir = '/Users/crooney/Documents/codes/pyDISORT/test/picaso_data/'
disort_dir = '/Users/crooney/Documents/codes/picaso/docs/notebooks/disort_data/'
# disortDE_dir = '/Users/crooney/Documents/codes/picaso/docs/notebooks/disort_data/DE/'
disort4_dir = '/Users/crooney/Documents/codes/picaso/docs/notebooks/disort_data/2_streams/'
SH2_dir = '/Users/crooney/Documents/codes/pyDISORT/test/picaso_data/SH2/'
SH4_dir = '/Users/crooney/Documents/codes/pyDISORT/test/picaso_data/SH4/'

for w0 in [.6]:
    filename = 'data_0.000_%.3f.pk' % w0
    Toon = pk.load(open(toon_dir + filename,'rb'))
    Disort_4 = pk.load(open(disort4_dir + filename,'rb'), encoding = 'bytes')
#     Disort_DE = pk.load(open(disortDE_dir + filename,'rb'), encoding = 'bytes')
    Disort = pk.load(open(disort_dir + filename,'rb'), encoding = 'bytes')
    SH2 = pk.load(open(SH2_dir + filename,'rb'), encoding = 'bytes')
    SH4 = pk.load(open(SH4_dir + filename,'rb'), encoding = 'bytes')

In [14]:
n=0
Toon['xint_at_top'][:,0,0]

array([0.04311634, 0.04266091, 0.04120737, 0.03800263, 0.03189158])

In [15]:
SH2['xint_at_top'][:,0,0]

array([0.0411573 , 0.04076376, 0.03950373, 0.03670278, 0.0312624 ])

In [16]:
SH4['xint_at_top'][:,0,0]

array([0.04219923, 0.04182542, 0.04062336, 0.03791445, 0.03241386])

In [17]:
Disort[b'xint_at_top'][:,0,0]

array([0.04253294, 0.04217136, 0.04101064, 0.03840519, 0.03314142])

In [ ]:
Disort_4[b'xint_at_top'][:,0,0]

In [ ]:
Toon['flux'][::2,0]

In [ ]:
SH2['flux'].shape

In [ ]:
SH4['intensity'][0,0,:,0]

In [ ]:
def L2_error(a,b):
    error = np.sqrt(np.sum((a-b)**2))/np.sqrt(np.sum(b**2))
    return error